Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls')),
    path('register/',include('Users.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name='Users'

urlpatterns = [
    path('',register,name='register'),
    path('login/',LoginView.as_view(template_name='Users/login.html') ,name='login'),
    path('logout/',LogoutView.as_view(template_name='Users/logout.html') ,name='logout'),
    path('profile/',profile,name='profile'),
    path('profile/edit',edit_profile,name='edit_profile'),
    path('profile/author/<int:pk>/',author_profile,name='author_profile'),
]

article/urls.py
from django.urls import path
from .views import *

app_name='article'

urlpatterns = [
    path('',index,name='index'),
    path('article/<int:pk>/',single_article,name='single_article'),
    path('article/category/<int:pk>/', categorised_article ,name='categorised_article'),
    path('article/post/',post_articleform  ,name='post_articleform'),
    path('article/create/',create_article  ,name='create_article'),
    path('article/update/<int:pk>/',UpdateArticle.as_view(),name='update_article'),
    path('article/delete/<int:pk>/',DeleteArticle.as_view(),name='delete_article'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class category(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name='Categorie'

class  Article(models.Model):

    author=models.ForeignKey(User, on_delete=models.CASCADE,default=1)

    category=models.ForeignKey(category,on_delete=models.CASCADE,default=1)
    title=models.CharField(max_length=100)
    content=models.TextField(max_length=8000)
    image=models.ImageField(upload_to='article_img/',default='default_img.jpg')#folder name  (pip install pillow)
    pub_date=models.DateField(auto_now=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("Users:profile")
    

article/forms.py
from django import forms
from django.forms import ModelForm 
from .models import *




class BootstrapImageWidget(forms.ClearableFileInput):
    def __init__(self, attrs=None):
        default_attrs = {'class': 'form-control shadow rouded-0'} 
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs) 

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article 
        fields=('category','title','content','image')

        widget={
            'category':forms.TextInput(attrs={'class': 'form-control shadow rounded-0','placeholder': 'Select a Category'}),
            'title': forms.TextInput(attrs={'class':'form-control shadow rounded-0'}),
            'content': forms.Textarea(attrs={'rows':'8', 'cols':'10','class':'form-control shadow rouded-0'}), 
        }

article/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.views.generic.edit  import UpdateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.

# context processor
def categories(request):
    categories=category.objects.all()

    return {
        'categories':categories,
    }
    

def index(request):

    all_articles=Article.objects.all()

    context={'articles':all_articles}
    return render(request,'article/index.html',context)



def single_article(request,pk):
    article=Article.objects.get(pk=pk)
    context={
        'article':article
    }
    return render(request,'article/article.html',context)

def categorised_article(request,pk):
    if pk==0:
        article=Article.objects.all()
        context={
        'articles':article,
        'category':'all'}
    else:
        categories=category.objects.get(pk=pk)
        
        article=Article.objects.filter(category=categories).all()# (that up variable name categories)
        context={
            'articles':article,
            'category':categories}
    return render(request,'article/categorised_article.html', context)

@login_required
def post_articleform(request):

    form=ArticleForm()
    if request.method=='POST':
      form=ArticleForm(request.POST,request.FILES)
      if form.is_valid():
          article=form.save(commit=False)
          article.author=request.user
          form.save()
          return redirect('article:single_article',pk=form.instance.id)
   
    context={
        'form':form
    }
    return render(request,'article/article_form.html',context)

def create_article(request):
    form=ArticleForm()
    if request.method=='POST':
        form=ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('article:index')
    context={
        'form':form
    }

    return render(request,"article/article_form.html",context)

class UpdateArticle(UpdateView):
    model=Article
    fields=['category','title','image','content']

    template_name_suffix="_update"

class DeleteArticle(DeleteView):
    model=Article
    success_url=reverse_lazy("Users:profile")

article/templates/article/article.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h2 class="mt-4" style="width:80%;">{{article.title}}</h2>
        <h5 class='m-2'>
            By:<a class="text-decoration-none" href="{% url "Users:author_profile"  article.author.id%} ">
                    {{article.author}}
                </a> on {{article.pub_date}} 
        </h5>
        <img  class='my-4'style="width:60%;" src="{{article.image.url}}" alt="">
        <p style="width:80%;">{{article.content}}</p>

    </div>

{% endblock content %}

article/templates/article/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class='container'>
        <form action='' method='post'>
            {% csrf_token %}
            <h2> Areb you sure you want to delete this article</h2>
            <button class='btn btn-danger' type='submit'>Delete</button>
        </form>
        
        
    </div>

{% endblock content %}

article/templates/article/article_form.html
{% extends "base.html" %}

{% block content %}
    <div class='container' >
        <h3 class="mx-1 my-3 fw-bold text-success">Post a article</h3>
        <form style="width:60%;" action='' method='POST' enctype='multi-part/form-data'> 
            {% comment %} enctype='multi-part/form-data' (To accept image) {% endcomment %}
            {% csrf_token %}
            {% for field in form  %}
            <div class=''>
                <div class='form-label mt-2 mx-1 fw-bold text-dark'>
                    {{field.label}}
                </div>
                <div class='my-2'>
                    {{field}}
                </div>
            </div>
            {% endfor %}
            
            <button type='submit' class='btn btn-success mx-1 rounded-0'>Submit</button>
        </form>
    </div>

{% endblock content %}

article/templates/article/article_update.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form="" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{form}}
            <button class='btn btn-success' type='submit'>Submit</button>
        </form>
    </div>

{% endblock content %}

article/templates/article/categorised_article.html
{% extends "base.html" %}


{% block content %}
<div class='container'>

    <h4 class="my-4">Categories: {{category}}</h4>
    <div class=''>
      {% for article in articles  %}
        <a class='row text-decoration-none text-dark my-3' href="{% url "article:single_article" article.id %}">
            <div class='image col-4'>
                <img style='width:85%' src="{{article.image.url}}" alt='Image of {{article.title}}'>
            </div>
            <div class='contents col-8'>
                <h5>{{article.title}}</h5>
                <h6>Published on :{{article.pub_date}}</h6>
                <p>{{article.content |truncatewords:75}}</p>

            </div>

        </a>
      
      {% endfor %}

    </div>
</div>



{% endblock content %}

article/templates/article/index.html
{% extends "base.html" %}

{% block content %}
<div class="container ">
    <h2 class='my-4'>All Articles</h2>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
        {% for article in articles %}
            <div class='col'>  
                <div class="card shadow"> 
                    <img src="{{article.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-dark">{{ article.title | truncatewords:5 }}</h5>
                        <p class="card-text">{{ article.content | truncatewords:20 }}</p>
                        <a href="{% url 'article:single_article' article.id %}" class="float-end text-decoration-none">Read more</a>
                    </div> 
                </div> 
            </div>  
        {% endfor %} 
    </div> 
</div> 

 {% comment %} {% for i in articles  %}

   {{i.title}} 
   {{i.content}}
   {{i.pub_date}}
   <img src='{{i.image.url}}'alt=''>

 {% endfor %} {% endcomment %}

{% endblock content %}