Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls')),
    path('register/',include('Users.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name='Users'

urlpatterns = [
    path('',register,name='register'),
    path('login/',LoginView.as_view(template_name='Users/login.html') ,name='login'),
    path('logout/',LogoutView.as_view(template_name='Users/logout.html') ,name='logout'),
    path('profile/',profile,name='profile'),
    path('profile/edit',edit_profile,name='edit_profile'),
    path('profile/author/<int:pk>/',author_profile,name='author_profile'),
]

article/urls.py
from django.urls import path
from .views import *

app_name='article'

urlpatterns = [
    path('',index,name='index'),
    path('article/<int:pk>/',single_article,name='single_article'),
    path('article/category/<int:pk>/', categorised_article ,name='categorised_article'),
    path('article/post/',post_articleform  ,name='post_articleform'),
    path('article/create/',create_article  ,name='create_article'),
    path('article/update/<int:pk>/',UpdateArticle.as_view(),name='update_article'),
    path('article/delete/<int:pk>/',DeleteArticle.as_view(),name='delete_article'),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name=models.CharField(max_length=50,blank=True,null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    contact_number=models.CharField(max_length=12,default='9999999999')
    image=models.ImageField(upload_to='profile_images/', default='profile.jpg')
    bio=models.TextField(max_length=400,blank=True,null=True)

    def __str__(self) -> str:
        return self.user.username 

Users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class NewRegisterForm(UserCreationForm):

    email=forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder':'Enter your Email', 'class':'form-control'}))
    username=forms.CharField( max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder':'Enter your Name', 'class':'form-control'}))
    password1=forms.CharField(label='password',required=True, widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Re-Enter password',required=True, widget=forms.PasswordInput(attrs={ 'class':'form-control'}))


    # User id already define in admin just need to impliment in meta class 
    class Meta:
        model=User

        fields=('username','email','password1','password2')
    def save(self,commit=True):
        user=super(NewRegisterForm,self).save(commit=False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user 

Users/views.py
from django.shortcuts import render,redirect
from .forms import *
from .models import *
from django.contrib.auth.models import User
from article.models import *


# Create your views here.

def register(request):
    if request.method=='POST':
        form=NewRegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            return redirect('article:login')
    else:
        form=NewRegisterForm()
    # form=NewRegisterForm()
    context={
        'forms':form
    }
    return render(request,'Users/register.html',context)

def  profile(request):
    articles=Article.objects.filter(author=request.user).all().order_by('-pub_date')
    context={
        'articles':articles
    }
    return render(request,'Users/profile.html',context)


def edit_profile(request):
    try:
        profile=request.user.profile
    except profile.DoesNotExist:
        profile=None
    
    if request.method=='POST':
        if profile:
            profile.user=request.user
            profile.first_name=request.POST.get("first_name")
            profile.last_name=request.POST.get("last_name")
            profile.contact_number=request.POST.get("contact_number")
            # profile.image=request.FILES.get("image")
            profile.bio=request.POST.get("bio")
            if request.FILES.get('image'):
                profile.image=request=request.FILES['image']
            profile.save()
        else:
            user=request.user
            first_name=request.POST.get("first_name")
            last_name=request.POST.get("last_name")
            contact_number=request.POST.get("contact_number")
            image=request.FILES.get("image")
            bio=request.POST.get("bio")

            profile=Profile(user=user,first_name=first_name,image=image,bio=bio,contact_number=contact_number,last_name=last_name)
            profile.save()

        return redirect("Users:profile")
    context={
        'profile':profile
    }

    return render(request,'Users/edit_profile.html',context)

def author_profile(request,pk):
    author=User.objects.get(pk=pk)
    article_count=Article.objects.filter(author=author).count()
    context={
        'author':author,
        'article_count':article_count
    }
    return render(request,'Users/author_profile.html',context)

Users/templates/Users/author_profile.html
{% extends "base.html" %}
{% block content %}
<div class='my-4 container'>
    <div style="width:45%" >
        <h6 class="text-dark fw-bold my-2">Username - {{author.username}}</h6>
        <p> Article count : {{article_count}} </p>
        {% if author.profile %}
            
            <div class="shadow rounded p-3 my-3">
                <img class="mb-4 rounded" style= "width:80%;" src="{{author.profile.image.url}}" alt="">
                <h6 class='text-dark'>{{author.profile.first_name}} {{author.profile.last_name}}</h6>
                <p>📞 : {{author.profile.contact_number}}</p>  
                <p>📧 : {{author.email}}</p> 
                <p>Bio : {{author.profile.bio}}</p> 
            </div> 
        {% else %} 
            ------ 
        {% endif %} 
    </div> 

</div> 

{% endblock content %}

Users/templates/Users/edit_profile.html
{% extends "base.html" %}
{% block content %}

<div style="width:70%;" class="container">
    <form action="" method= "POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div class="form-group my-2">
            <label class="form-label" for="first_name">First name</label> 
            <input class="form-control" type="text" id="first_name" name="first_name" value={{profile.first_name}}>  
        </div> 
        <div class="form-group my-2">
            <label class="form-label" for="last_name">Last name</label>
            <input class="form-control" type="text" id="last_name" name="last_name" value= {{profile.last_name}}> 
        </div> 
        <div class="form-group my-2">
            <label class="form-label" for="contact_number">Contact number</label>
            <input class="form-control" type="text" id="contact_number" name="contact_number" value={{profile.contact_number}}> 
        </div> 
        {% if profile.image.url %}
        <span>
            <p>Current image</p>
            <img class="my-2" style="width:20%;" src="{{profile.image.url}}" alt=""> 
        </span>
        {% endif %}  
        <div class="form-group my-2">
            <label class="form-label" for="image">Image</label> 
            <input class="form-control" type="file" id="image" name="image">   
        </div> 
        <div class="form-group my-2">
            <label class="form-label" for="">Bio</label> 
            <textarea class="form-control" name="bio" id="bio" cols="30" rows="10">{{profile.bio}}</textarea>  
        </div>  


        <button class="btn btn-success" type="submit">Save</button> 
    </form>
</div>

{% endblock content %}

Users/templates/Users/login.html
{% extends "base.html" %}

{% block content %}
    <div style='height:400px;' class='container d-flex justify-content-center p-5'>
        <div class='login-form'>
            <h2 class='my-3 fw-bold text-success'>Login!</h2>
            <form action='' method='POST'>
            {% csrf_token %}
            <div class='username'>
                <div class="form-label mx-2 fw-bold text-dark">
                    {{form.username.label}}
                </div>
                <div class="form-control border-0">
                    {{form.username}} 
                </div> 
            </div> 
            <div class= 'password'>
                <div class="form-label mx-2 fw-bold text-dark">
                    {{form.password.label}}
                </div>
                <div class="form-control border-0">
                    {{form.password}} 
                </div> 
            </div>
            <button class="btn btn-success m-2" type="submit">Login</button> 
        </form>
    
        
    
        <div class="d-flex">
            <h6 class='mt-2 fw-semibold mx-2'>Dont have an account?</h6>
            <a class='mx-3 fs-5' href="{% url "Users:register" %}">Register</a> 
        </div> 
    
    </div>
</div>
    

{% endblock content %}

Users/templates/Users/logout.html
{% extends "base.html" %}


{% block content %}

    <div class="container">
        <h3 class='fw-semibold m-4'>Loged out , Login and go</h3>
    </div>


{% endblock content %}

Users/templates/Users/profile.html
{% extends "base.html" %}

{% block content %}

<div class='my-4 row container'>
    <div id='profile' style="width:45%" class='col-lg-4' >
        <h6 class="text-dark fw-bold my-2">Username - {{user.username}}</h6>
        {% if user.profile %}
            <a class="btn btn-warning p-0 px-2 float-end" href="{% url "Users:edit_profile" %}">Edit</a>
            <div class="shadow rounded p-3 my-3">
                <img class="mb-4 rounded" style= "width:80%;" src="{{user.profile.image.url}}" alt="">
                <h6 class='text-dark'>{{user.profile.first_name}} {{user.profile.last_name}}</h6>
                <p>📞 : {{user.profile.contact_number}}</p>  
                <p>📧 : {{user.email}}</p> 
                <p>Bio : {{user.profile.bio}}</p> 
            </div> 
        {% else %} 
            <a class="btn btn-success p-0 px-2" href="{% url "Users:edit_profile" %}">Create</a> 
        {% endif %} 
    </div> 
        
        <div id='all_posts' class="col-lg-6 ">
            <h3>All Posts</h3>
            <div>
                {% for post in articles  %}
                <div  class='row'>
                        <div  id='image' class='col-3'>
                            <img style='width:100%;' src="{{post.image.url}} "/>
                        </div>
                        <div id='content' class='col-9'>
                            <h5>{{post.title}}</h5>
                            <p>{{post.content | truncatewords:10}}</p>
                        </div>
                        <div class='col-2'>
                            <a href="{% url "article:update_article" post.id %} ">Edit</a>
                            <a href="{% url "article:delete_article" post.id %} ">Delete</a>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </div>
</div>

{% endblock content %}

Users/templates/Users/register.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2 class="my-4">Register User</h2> 

    <form style="width:60%;" action="" method="POST">
        {% csrf_token %} 
        <div class="">
            {{ forms }} 
        </div>
        <button class="btn btn-success my-3" type="submit">Submit</button>
    </form> 

    <div class="d-flex">
        <h5 class='mt-2 fw-semibold mx-2'>Alredy have an account?</h5>
        <a class='mx-3 fs-5'  href="{% url "Users:login" %}">Login</a>
    </div>
    
</div> 

{% endblock content %}