Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls')),
    path('register/',include('Users.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name='Users'

urlpatterns = [
    path('',register,name='register'),
    path('login/',LoginView.as_view(template_name='Users/login.html') ,name='login'),
    path('logout/',LogoutView.as_view(template_name='Users/logout.html') ,name='logout'),
    path('profile/',profile,name='profile'),
    path('profile/edit',edit_profile,name='edit_profile'),
    path('profile/author/<int:pk>/',author_profile,name='author_profile'),
]

article/urls.py
from django.urls import path
from .views import *

app_name='article'

urlpatterns = [
    path('',index,name='index'),
    path('article/<int:pk>/',single_article,name='single_article'),
    path('article/category/<int:pk>/', categorised_article ,name='categorised_article'),
    path('article/post/',post_articleform  ,name='post_articleform'),
    path('article/create/',create_article  ,name='create_article'),
    path('article/update/<int:pk>/',UpdateArticle.as_view(),name='update_article'),
    path('article/delete/<int:pk>/',DeleteArticle.as_view(),name='delete_article'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} </title>

    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> {% endcomment %}

    <link rel="stylesheet" href="https://bootswatch.com/5/minty/bootstrap.min.css"> 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- JavaScript -->

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  <!-- JavaScript Popper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <!-- Bootstrap Max CDN --> 

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    {% block nav %}

    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
        <div class="container-fluid"> 
          <a class="navbar-brand fw-bolder text-dark" href="{% url "article:index" %}">CuriousChronicles</a> 
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "article:index" %}">Home</a> 
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:post_articleform" %}">Post</a>  
              </li>


              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu"> 

                  {% for category in categories %}
                    <li><a class="dropdown-item" href="{% url "article:categorised_article" category.id %}">{{category}}</a></li>  
                  {% endfor %} 

                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "article:categorised_article" 0 %}">All</a></li>  
                </ul>
              </li>

              {% comment %} login logout btn  {% endcomment %}
              {% comment %} {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link text-decoration-none" href="{% url "users:profile" %}">Profile</a> 
                </li>     
              
                <li class="nav-item"> 
                  <form class="nav-link" action="{% url "users:logout" %}" method="POST"> 
                    {% csrf_token %}
                    <button class='btn btn-outline-danger py-0 border-0' type="submit">Logout</button>  
                  </form>   
                </li> 

              {% else %}
                
                <li class="nav-item ">
                  <form class="nav-link" action="{% url "users:login" %}" method="POST"> 
                    {% csrf_token %}
                    <button class='btn btn-outline-success py-0 fw-bold border-0' type="submit">Login</button>  
                  </form>  
                </li> 
                <span class="mt-2">|</span>
                <li class="nav-item ">
                  <a class="nav-link text-decoration-none text-success m-0" href="{% url "users:register" %}">Register</a> 
                </li>
              {% endif %}   {% endcomment %} 
            </ul>
            
            <form class="d-flex" role="search">
              <input class="form-control me-2 rounded-0" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success rounded-0" type="submit">Search</button>
            </form>

            <div class="auth d-flex mx-3">
              {% if user.is_authenticated %}
                <a class="nav-link text-decoration-none mx-3" href="{% url "Users:profile" %}">Profile</a>  
                <span class="">|</span>    
                <form class="nav-link" action="{% url "Users:logout" %}" method="POST"> 
                  {% csrf_token %}
                  <button class='btn btn-outline-danger py-0 border-0' type="submit">Logout</button>  
                </form>   
              {% else %} 
                <form class="nav-link" action="{% url "Users:login" %}" method="POST">  
                  {% csrf_token %}
                  <button class='btn btn-outline-dark py-0 border-0 mx-1' type="submit">Login</button>  
                </form>  
                <span class="">|</span>  
                <a class="nav-link text-decoration-none text-success mx-2" href="{% url "Users:register" %}">Register</a> 
              {% endif %}  
            </div>
          </div>
        </div>
      </nav>
 
    {% endblock nav %}

    {% block content %}{% endblock content %}

    {% block footer %}{% endblock footer %}
</body>
</html>